service: my-lambda-service
frameworkVersion: '3'

useDotenv: true

provider:
    name: aws
    runtime: nodejs20.x
    region: us-west-1

package:
    patterns:
        - '!node_modules/.pnpm/**'

functions:
    api:
        handler: src/index.handler
        events:
            - httpApi:
                  path: /hello
                  method: get

plugins:
    - serverless-plugin-typescript
