service: my-lambda-service
frameworkVersion: '3'

useDotenv: true

provider:
    name: aws
    runtime: nodejs20.x
    region: us-west-1
    httpApi:
        authorizers:
            jwtCognitoAuthorizer:
                type: jwt
                identitySource: $request.header.Authorization
                issuerUrl: ${env:ISSUER_URL}
                audience:
                    - ${env:AUDIENCE}

functions:
    queryProducts:
        handler: src/queryProducts.handler
        events:
            - httpApi:
                  path: /products
                  method: get
        iamRoleStatements:
            - Effect: 'Allow'
              Action:
                  - 'dynamodb:GetItem'
              Resource: 'arn:aws:dynamodb:${self:provider.region}:*:table/${env.DYNAMODB_PRODUCTS_TABLE_NAME}'
    getProductByName:
        handler: src/getProductByName.handler
        events:
            - httpApi:
                  path: /product/{name}
                  method: get
        iamRoleStatements:
            - Effect: 'Allow'
              Action:
                  - 'dynamodb:GetItem'
              Resource: 'arn:aws:dynamodb:${self:provider.region}:*:table/${env.DYNAMODB_PRODUCTS_TABLE_NAME}'

plugins:
    - serverless-esbuild
    - serverless-iam-roles-per-function

custom:
    esbuild:
        packager: pnpm
        bundle: true
        minify: true
        keepNames: true
