service: my-lambda-service
frameworkVersion: '3'

useDotenv: true

provider:
    name: aws
    runtime: nodejs20.x
    region: us-west-1

functions:
    api:
        handler: dist/index.handler
        events:
            - httpApi:
                  path: /
                  method: get
